services:
  - type: web
    name: careerdock-backend
    env: node
    rootDir: careerdock-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
